import type { ImportItemConfig } from './types';

export const IMPORT_ITEMS: ImportItemConfig[] = [
  {
    code: 'employees',
    title: '员工档案与组织架构',
    description: '导入员工档案，自动创建 工区/部门/班组 三层组织（缺则建）。',
    dependsOn: '无（最先导入，建立名册）',
    apiEndpoint: '/api/admin/import/employees',
    hasScorePreview: false,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码', '员工编号'] },
      { key: 'fullName', label: '姓名', required: true, headerAliases: ['员工姓名'] },
      { key: 'workArea', label: '工区', required: true, hint: '含总部及各工区', headerAliases: ['所在单位', '单位'] },
      { key: 'department', label: '部门', required: true },
      { key: 'team', label: '班组', required: false, headerAliases: ['班组/处室', '处室'] },
      { key: 'position', label: '岗位', required: false },
      { key: 'gender', label: '性别', required: false },
    ],
  },
  {
    code: 'basic',
    title: '基本素质三维度',
    description: '一次上传算出技能/职称/绩效三条事实，绩效按三年 A/B 组合计分。推荐上传合并后的《基本素质信息_合并》.xlsx。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/basic',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'fullName', label: '姓名', required: false },
      { key: 'skill', label: '技能等级', required: false },
      { key: 'title', label: '职称等级', required: false, headerAliases: ['专业技术资格等级'] },
      { key: 'perf2023', label: '绩效2023', required: false, headerAliases: ['2023年考核等级'] },
      { key: 'perf2024', label: '绩效2024', required: false, headerAliases: ['2024年考核等级'] },
      { key: 'perf2025', label: '绩效2025', required: false, headerAliases: ['2025年考核等级'] },
    ],
  },
  {
    code: 'tickets',
    title: '两票执行',
    description: '上传《工作现场-两票执行》.xlsx，分别读取「操作票」「工作票」工作表，按积分表 3.1 聚合每人全年原始分；最终折算在汇总阶段完成。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/tickets',
    requireFullBatch: true,
    hasScorePreview: true,
    fields: [],
  },
  {
    code: 'defects',
    title: '缺陷治理',
    description: 'MATRIX_SUM：角色×缺陷等级计分，封顶12，含多人拆分与合作标记。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/defects',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'role', label: '角色', required: false, hint: '第一发现人/共同发现人/第一处理人/共同处理人' },
      { key: 'eventType', label: '事件类型', required: false, hint: '发现/处理' },
      { key: 'defectLevel', label: '缺陷等级', required: false, hint: '危急/严重/一般' },
      { key: 'defectRef', label: '缺陷编号', required: false },
      { key: 'eventDate', label: '事件日期', required: false },
    ],
  },
  {
    code: 'safety',
    title: '安全贡献',
    description: 'SHARE 均分：按事件分组，第一发现人3分/次，其他发现人均分。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/safety',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'role', label: '角色', required: false, hint: '第一发现人/共同发现人' },
      { key: 'faultCount', label: '故障次数', required: false },
      { key: 'incidentId', label: '事件编号', required: false },
      { key: 'eventDate', label: '事件日期', required: false },
    ],
  },
  {
    code: 'tech-textbook',
    title: '技术贡献·教材/题库/课件',
    description: '参加公司级及以上教材编制、题库开发、课件开发：3 分/次。封顶 12（与其他技术贡献子项合计）。',
    dependsOn: '依赖员工档案名册；建议先合并单元格展开（已自动）',
    apiEndpoint: '/api/admin/import/tech',
    apiEndpointParams: { kind: 'textbook' },
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'projectName', label: '项目/教材名', required: false, headerAliases: ['教材名称', '题库名称', '课件名称'] },
      { key: 'role', label: '角色', required: false },
    ],
  },
  {
    code: 'tech-regulation',
    title: '技术贡献·运规编写/会审',
    description: '编制公司级及以上《运规》：2 分/项。**含合并单元格的源文件已自动展开**，同一员工参与多个规程会分别计分。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/tech',
    apiEndpointParams: { kind: 'regulation' },
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'projectName', label: '规程名称', required: false, headerAliases: ['规程名称'] },
      { key: 'role', label: '运规主要工作', required: false, headerAliases: ['《运规》主要工作', '主要工作'] },
    ],
  },
  {
    code: 'tech-ticket-revision',
    title: '技术贡献·两票修订/审查',
    description: '编制公司级及以上《两票》：2 分/项（修订主要人员、审查人员都计分）。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/tech',
    apiEndpointParams: { kind: 'ticket-revision' },
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'projectName', label: '《两票》名称', required: false },
      { key: 'role', label: '《两票》职务', required: false, headerAliases: ['两票职务'] },
    ],
  },
  {
    code: 'competition',
    title: '竞赛比武',
    description: '技能竞赛/调考/知识竞赛：按级别（国网/省公司）自动判分。国网 10/5/5；省 5/2/2。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/competition',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'award', label: '奖项', required: false },
      { key: 'level', label: '级别', required: false, hint: '国网/省公司' },
      { key: 'category', label: '类别', required: false, hint: '技能竞赛/调考/知识竞赛' },
    ],
  },
  {
    code: 'innovation',
    title: '创新奖项',
    description: '管理/科技创新 国网 5 省 3；QC/五小 国网 4 省 2。按奖项名自动判定类别。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/innovation',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'award', label: '奖项', required: false },
      { key: 'level', label: '级别', required: false, hint: '国网/省公司' },
      { key: 'project', label: '项目', required: false },
    ],
  },
  {
    code: 'patent',
    title: '发明专利',
    description: '前 4 位发明人按序 4/3/2/1 分。源数据每行 1 个专利的 4 位发明人会自动展开为 4 条记录。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/patent',
    hasScorePreview: true,
    fields: [
      { key: 'patentName', label: '专利名称', required: true, headerAliases: ['原始申请(专利权)人', '专利名称'] },
      // inventorCols 由后端固定为 发明人1~4 + 人员编号 4 列（自动）
    ],
  },
  {
    code: 'violation',
    title: '违章扣分',
    description: '严重违章 直接 -10/连带 -5；一般违章 直接 -5/连带 -2.5。按等级和人员类型自动判分。',
    dependsOn: '依赖员工档案名册',
    apiEndpoint: '/api/admin/import/violation',
    hasScorePreview: true,
    fields: [
      { key: 'employeeNo', label: '工号', required: true, headerAliases: ['人员编号', '人员编码'] },
      { key: 'employeeName', label: '姓名', required: false },
      { key: 'level', label: '等级', required: false, hint: '严重/一般' },
      { key: 'role', label: '人员类型', required: false, hint: '直接责任人/连带责任人' },
      { key: 'description', label: '作业项目/发现的问题', required: false },
      { key: 'eventDate', label: '日期', required: false },
    ],
  },
];

export function getItemConfig(code: string): ImportItemConfig {
  return IMPORT_ITEMS.find((i) => i.code === code) ?? IMPORT_ITEMS[0];
}
